services:
  auth-service:
    container_name: auth-service
    build:
      context: auth-service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - auth-service/.env
    environment:
      - DB_URL=postgres://user:password@auth-db:5432/authdb?sslmode=disable
    depends_on:
      - auth-db
    networks:
      - auth-network

  auth-db:
    container_name: auth-db
    image: postgres:latest
    restart: always
    env_file:
      - auth-service/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - auth-network

  blog-service:
    container_name: blog-service
    build:
      context: blog-service/
      dockerfile: Dockerfile
    env_file:
      - blog-service/.env
    environment:
      -  DB_URL=postgres://user:password@blog-db:5432/blogdb?sslmode=false
    ports:
      - "8082:8080"
    depends_on:
      - blog-db
    networks:
      - blog-network
  
  blog-db:
    container_name: blog
    image: postgres:latest
    restart: always
    env_file:
      - blog-service/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - blog-network


networks:
  auth-network:
    driver: bridge
  blog-network:
    driver: bridge

volumes:
  auth-db-data:

